### ISSUE TITLE
How many DID for for each contribution type?

### ISSUE THREAD

**Issue by DIDHAV** [Distense/contracts#2]
This is about the number of DID we will issue for each contribution type (#1).  Obviously there are implications about the _absolute_ number and _relative_ quantity.
- Issues: 1
- PRs: 100 (obviously multiple commits are implied)
- Features: 1000

**Comment by Sulejman** [comment]
How would different project prices be handles if these rules were same for all projects?
And also, some features would be more valuable for project (or present more work) so it should be handled too.
