### ISSUE TITLE
Contract Architecture (number of contracts and files)

### ISSUE THREAD

**Issue by DIDHAV** [Distense/contracts#6]
There are recommendations to make contracts small, and some bigger and in one place/file.  What are the pros and cons of each approach and what approach should Distense take with our contracts?

This issue is about the topics found [here](https://github.com/ConsenSys/smart-contract-best-practices#fundamental-tradeoffs-simplicity-versus-complexity-cases).  We will definitely need to be able to upgrade at least the token contract (as in reissue the same number of a technically new token with a new contract).

**Comment by DIDHAV** [comment]
If stuff isn't in one place it will be hard to read how different code will interact with one another.

**Comment by Sulejman** [comment]
There is lot of decisions to be made here and it cannot be fast process. However, we have one constant in everything and that is once you deploy contracts, they cannot be updated anymore ... only replaced. 
Maybe good solution would be to have token contracts (for DID and HAV), as they present the core of Distense written once, properly, keeping it simple (with basic options).
And for the contract/s which would be responsible for ruling on how much would people get paid for what, voting, decision making, distribution etc, good idea would be to implement Relay contract (to keep same address) like proposed here: https://ethereum.stackexchange.com/questions/2404/upgradeable-smart-contracts
Behind relay contract which would act as proxy we may implement and change different rules based on community discussions and needs.
