### ISSUE TITLE
How to Map Contribution to Ethereum Address 

### ISSUE THREAD

**Issue by DIDHAV** [Distense/contracts#8]
One question is where does the user provide their `ethAddress` so we can issue DID for their contribution.  For hackers we should still have it be easier but for those who are not already developers we need a really easy way for them to add their Ethereum address.

Design goals: 

- Minimize number of queries, iterations and different URIs that may need to be queried
- Ease of use for non-technical contributors

Options:

1. Manually add an `ethAddress` to commit message on the second/last line of the commit message
2. Queryable public gist that contains an ethAddress
3. Git config repo addition: `git config user.ethAddress "0xbeefbeefbeefbeefbeefbeefbeef"`
4. Hook in each repo that auto adds `ethAddress` to the end of each commit message
    - This could auto add the repo-specific `git config user.ethAddress` into each commit
5. On-chain Distense profile
    - User calls contract function which maps an `ethAddress` to Github username.  They can also provide their country and other information (though limited due to gas costs). The `ethAddress` is then easy to get on-chain when querying Github api which already provides committer `user.login` (see [example API query](https://api.github.com/repos/octocat/Hello-World/pulls))
6. Provide ethAddress in pull request message which is available in `.title`, since pull requests are what we will likely end up rewarding.  (Since everyone will not push to master but submit a pull request)
7. Set `git config user.name` to include either just an `ethAddress` or both the Github username and the `ethAddress`
    - This is obviously hacky but would be simple and effective.  
    - Possible that Github rejects the contents of `user.name` (git doesn't, tried)

**Comment by Sulejman** [comment]
Adding ethAddress to commit message in some format seems like practical way of doing it but manual isn't an option, it should be one time setup.

**Comment by cpetzold** [comment]
I like the idea of using a specially formatted `CONTRIBUTORS` file in each repository that lists github usernames with eth address. This has the added benefits of contributors being localized to a given project, and could be used to onboard new contributors by giving the 1DID reward for getting a PR merged with their username/address added.

Here's an example from golang: https://github.com/golang/go/blob/master/CONTRIBUTORS

It could look something like:
```
# Names should be added to this file like so:
#     Individual's github username <eth address>

DIDHAV <0xa250e7ef194a8a91d46795b475f17b0519c5a835>
Sulejman <0x64ddbbfd9c9600d2be56e298b1c1df4e4b5c9b71>
cpetzold <0x2a62c2f8BB3e77a98fD874e80f8A1E5137edBE8e>
⋮
```

It may be bad to change the generally accepted format of a contributor (`Name <email address>`), and its not quite as nice to work with if we wanted to add more metadata to a "contributor". Using something more structured like yaml or json may be more future proof. Something like:

```yaml
- github: DIDHAV
  eth: 0xa250e7ef194a8a91d46795b475f17b0519c5a835

- github: Sulejman
  eth: 0x64ddbbfd9c9600d2be56e298b1c1df4e4b5c9b71

- github: cpetzold
  eth: 0x2a62c2f8BB3e77a98fD874e80f8A1E5137edBE8e
  name: Conner Petzold
  email: cpetzold@gmail.com
```

It may be good to give the contributor the option of being associated by either their github username or their email. If we were to eventually support git more generically, using email would make more sense.

**Comment by JohnAllen** [comment]
I like this idea, probably the second version more.  This is because we could allow users to essentially create a profile there, like I think we were considering doing in a web interface.  Although this would need to be manually checked, as someone could come along and add their Ethereum address under many peoples' github usernames.  We could limit the number of people that could do this to stay 100,500, 1000 and do PRs where we actually do verify that the Github username is the one they enter in this CONTRIBUTORS file.
